[versions]
browser = "1.9.0"
composeScrollbars = "1.0.4"
haze = "1.7.0"
jsoup = "1.21.2"
kotlin-version = "2.2.21"
agp-version = "8.13.1"
compose-version = "1.10.0-beta01"
ktor-version = "3.3.2"
kotlinx-datetime = "0.7.1"
datastore-version = "1.1.7"
navigationCompose = "2.9.1"
lifecycleViewmodelCompose = "2.9.6"
paging-version = "3.3.6"
kamel-image = "1.0.8"
kotlinx-coroutines-core = "1.10.2"
sonner = "0.3.8"
androidx-material = "1.13.0"

ksp = "2.3.2"
androidx-room = "2.8.3"

cmp-nav3 = "1.0.0-alpha04"
cmp-navevent = "1.0.0-beta01"
cmpLifecycle = "2.10.0-alpha04"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp-version" }
android-library = { id = "com.android.library", version.ref = "agp-version" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-version" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin-version" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "androidx-room" }

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.7.1" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "browser" }
androidx-core = { module = "androidx.core:core-ktx", version = "1.17.0" }
androidx-activity-compose = "androidx.activity:activity-compose:1.11.0"
composeScrollbars = { module = "com.github.GIGAMOLE:ComposeScrollbars", version.ref = "composeScrollbars" }
datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "datastore-version" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences-core", version.ref = "datastore-version" }
datastore-core-okio = { group = "androidx.datastore", name = "datastore-core-okio", version.ref = "datastore-version" }
haze = { module = "dev.chrisbanes.haze:haze", version.ref = "haze" }
haze-materials = { module = "dev.chrisbanes.haze:haze-materials", version.ref = "haze" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycleViewmodelCompose" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidx-room" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidx-room" }
androidx-room-paging = { group = "androidx.room", name = "room-paging", version.ref = "androidx-room" }
paging-runtime = { module = "androidx.paging:paging-common", version.ref = "paging-version" }
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor-version" }
ktor-jvm = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor-version" }
ktor-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor-version" }
ktor-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor-version" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kamel-image = { module = "media.kamel:kamel-image-default", version.ref = "kamel-image" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines-core" }
sonner = { module = "io.github.dokar3:sonner", version.ref = "sonner" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycleViewmodelCompose" }
androidx-material = { group = "com.google.android.material", name = "material", version.ref = "androidx-material" }
cmp-navigation3-ui = { group = "org.jetbrains.androidx.navigation3", name = "navigation3-ui", version.ref = "cmp-nav3" }
cmp-lifecycle-viewmodel-navigation3 = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "cmpLifecycle" }
cmp-navigationevent-compose = { module = "org.jetbrains.androidx.navigationevent:navigationevent-compose", version.ref = "cmp-navevent" }