[versions]
appVersion = "4.4.4"
alarmee = "2.6.0"
biometricauth = "1.1.0"
biometricVersion = "1.4.0-alpha05"
blurhashVersion = "0.0-4-ALPHA"
browser = "1.9.0"
composeMultiplatformMediaPlayerVersion = "1.0.52"
composeScrollbars = "1.0.4"
composewebview = "1.0.0-alpha-05"
gitlive = "2.4.0"
haze = "1.7.1"
kmpIo = "0.2.3"
kotlin-version = "2.3.0"
agp-version = "9.1.0-alpha04"
compose-version = "1.11.0-alpha01"
kotlinMultiplatformAppdirsVersion = "2.0.0"
kotlinNativeZxing = "2.3.0-SNAPSHOT"
kotlinxCollectionsImmutableVersion = "0.4.0"
ksoup = "0.2.5"
ktor-version = "3.3.3"
kotlinx-datetime = "0.7.1"
datastore-version = "1.2.0"
material3Version = "1.11.0-alpha01"
lifecycleViewmodelCompose = "2.10.0-alpha07"
materialKolorVersion = "4.0.5"
okio = "3.16.4"
paging-version = "3.4.0-beta01"
kamel-image = "1.0.8"
kotlinx-coroutines-core = "1.10.2"
androidx-material = "1.13.0"

ksp = "2.3.4"
androidx-room = "2.8.4"
permissions = "0.20.1"
sqlite = "2.6.2"

cmp-nav3 = "1.1.0-alpha01"
cmp-navevent = "1.0.0"
cmpLifecycle = "2.10.0-alpha07"
cmp-nav3-material3 = "1.3.0-alpha03"

koin = "4.2.0-beta2"

filekit = "0.12.0"

qrose = "1.0.1"
scanner = "0.6.0"
javase = "3.5.4"
coreVersion = "3.5.4"
barcodeScanning = "17.3.0"

connectivity = "2.4.0"

aboutLibraries = "13.2.1"
workRuntimeKtx = "2.11.0"

easylauncher = "6.4.1"

googleGmsGoogleServices = "4.4.4"
googleFirebaseCrashlytics = "3.0.6"
googlePerformancePlugin = "2.0.2"
firebaseBom = "34.7.0"
firebase-cocoapods = "11.8.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp-version" }
android-library = { id = "com.android.library", version.ref = "agp-version" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-version" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin-version" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "androidx-room" }
aboutLibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutLibraries" }
easylauncher = { id = "com.starter.easylauncher", version.ref = "easylauncher" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }
google-firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "googleFirebaseCrashlytics" }
google-firebase-performance = { id = "com.google.firebase.firebase-perf", version.ref = "googlePerformancePlugin" }

[libraries]
alarmee = { module = "io.github.tweener:alarmee", version.ref = "alarmee" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.7.1" }
androidx-biometric = { module = "androidx.biometric:biometric", version.ref = "biometricVersion" }
androidx-biometric-compose = { module = "androidx.biometric:biometric-compose", version.ref = "biometricVersion" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "browser" }
androidx-core = { module = "androidx.core:core-ktx", version = "1.17.0" }
androidx-activity-compose = "androidx.activity:activity-compose:1.12.2"
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
biometricauth = { module = "io.github.zaval:biometricauth", version.ref = "biometricauth" }
compose-multiplatform-media-player = { module = "network.chaintech:compose-multiplatform-media-player", version.ref = "composeMultiplatformMediaPlayerVersion" }
blurhash = { module = "io.github.brys0:blurhash", version.ref = "blurhashVersion" }
composeScrollbars = { module = "com.github.GIGAMOLE:ComposeScrollbars", version.ref = "composeScrollbars" }
composewebview = { module = "io.github.kdroidfilter:composewebview", version.ref = "composewebview" }
datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "datastore-version" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences-core", version.ref = "datastore-version" }
datastore-core-okio = { group = "androidx.datastore", name = "datastore-core-okio", version.ref = "datastore-version" }
gitlive-firebase-crashlytics = { module = "dev.gitlive:firebase-crashlytics", version.ref = "gitlive" }
gitlive-firebase-analytics = { module = "dev.gitlive:firebase-analytics", version.ref = "gitlive" }
gitlive-firebase-perf = { module = "dev.gitlive:firebase-perf", version.ref = "gitlive" }
haze = { module = "dev.chrisbanes.haze:haze", version.ref = "haze" }
haze-materials = { module = "dev.chrisbanes.haze:haze-materials", version.ref = "haze" }
kmp-io = { module = "io.github.skolson:kmp-io", version.ref = "kmpIo" }
kotlin-multiplatform-appdirs = { module = "ca.gosyer:kotlin-multiplatform-appdirs", version.ref = "kotlinMultiplatformAppdirsVersion" }
kotlin-native-zxing = { module = "io.github.zxing-cpp:kotlin-native", version.ref = "kotlinNativeZxing" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutableVersion" }
ksoup = { module = "com.fleeksoft.ksoup:ksoup", version.ref = "ksoup" }
material-kolor = { module = "com.materialkolor:material-kolor", version.ref = "materialKolorVersion" }
material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3Version" }
lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycleViewmodelCompose" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidx-room" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidx-room" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
paging-runtime = { module = "androidx.paging:paging-common", version.ref = "paging-version" }
paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging-version" }
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor-version" }
ktor-jvm = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor-version" }
ktor-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor-version" }
ktor-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor-version" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kamel-image = { module = "media.kamel:kamel-image-default", version.ref = "kamel-image" }
kamel-image-bitmap-resizing = { module = "media.kamel:kamel-decoder-image-bitmap-resizing", version.ref = "kamel-image" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines-core" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines-core" }
androidx-material = { group = "com.google.android.material", name = "material", version.ref = "androidx-material" }

androidx-sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }

cmp-navigation3-ui = { group = "org.jetbrains.androidx.navigation3", name = "navigation3-ui", version.ref = "cmp-nav3" }
cmp-lifecycle-viewmodel-navigation3 = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "cmpLifecycle" }
cmp-navigationevent-compose = { module = "org.jetbrains.androidx.navigationevent:navigationevent-compose", version.ref = "cmp-navevent" }
cmp-material3-adaptive-nav3 = { module = "org.jetbrains.compose.material3.adaptive:adaptive-navigation3", version.ref = "cmp-nav3-material3" }

koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-compose = { module = "io.insert-koin:koin-compose" }
koin-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel" }
koin-nav3 = { module = "io.insert-koin:koin-compose-navigation3" }

koin-workmanager = { module = "io.insert-koin:koin-androidx-workmanager" }

filekit-core = { module = "io.github.vinceglb:filekit-core", version.ref = "filekit" }
filekit-dialogs = { module = "io.github.vinceglb:filekit-dialogs", version.ref = "filekit" }
filekit-dialogs-compose = { module = "io.github.vinceglb:filekit-dialogs-compose", version.ref = "filekit" }

permissions = { module = "dev.icerock.moko:permissions", version.ref = "permissions" }
permissions-notifications = { module = "dev.icerock.moko:permissions-notifications", version.ref = "permissions" }
qrose = { module = "io.github.alexzhirkevich:qrose", version.ref = "qrose" }
scanner = { module = "io.github.kalinjul.easyqrscan:scanner", version.ref = "scanner" }

barcode-scanning = { module = "com.google.mlkit:barcode-scanning", version.ref = "barcodeScanning" }
zxing-javase = { module = "com.google.zxing:javase", version.ref = "javase" }
zxing-core = { module = "com.google.zxing:core", version.ref = "coreVersion" }

coroutinesPlayServices = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinx-coroutines-core" }

connectivity-core = { module = "dev.jordond.connectivity:connectivity-core", version.ref = "connectivity" }
connectivity-device = { module = "dev.jordond.connectivity:connectivity-device", version.ref = "connectivity" }
connectivity-android = { module = "dev.jordond.connectivity:connectivity-android", version.ref = "connectivity" }
connectivity-apple = { module = "dev.jordond.connectivity:connectivity-apple", version.ref = "connectivity" }
connectivity-http = { module = "dev.jordond.connectivity:connectivity-http", version.ref = "connectivity" }
connectivity-compose = { module = "dev.jordond.connectivity:connectivity-compose", version.ref = "connectivity" }
connectivity-compose-device = { module = "dev.jordond.connectivity:connectivity-compose-device", version.ref = "connectivity" }
connectivity-compose-http = { module = "dev.jordond.connectivity:connectivity-compose-http", version.ref = "connectivity" }

# Core module (required for accessing library data)
aboutlibraries-core = { module = "com.mikepenz:aboutlibraries-core", version.ref = "aboutLibraries" }
# Compose UI modules (choose one or both)
aboutlibraries-compose-core = { module = "com.mikepenz:aboutlibraries-compose-core", version.ref = "aboutLibraries" } # Common compose core
aboutlibraries-compose-m3 = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "aboutLibraries" }      # Material 3 UI

firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-perf = { module = "com.google.firebase:firebase-perf" }
